blank_issues_enabled: false
contact_links:
  - name: Contribution guidelines
    url: https://github.com/mohitkumhar/450-dsa/blob/main/CONTRIBUTING.md
    about: Read this before asking to be assigned to a GSSoC issue.
